### PR TITLE
Feature/sending tx mode

### PR DESCRIPTION
**Pull request by zenit70**
- Added optional `mode` param to `createSignAndSendTx` method.
- Renamed property `iso8601creationTimestamp` to `timestamp`.
- Enabled and updated commented tests.
- Remove unused imports.
- Added missing `static` to `DocsHelper` functions.
- Updated docs.

### CODE REVIEW

**Review by pasqenr — COMMENTED** [review]
To pass the Travis build should be enough to run `dartfmt` on the file `test/id/did_document_helper_test.dart`.

About the `mode` parameter I think that it's too error-prone as `String`. Maybe an `enum` is a better choice? For example:
```dart
enum BroadcastingMode {
  sync,
  async,
  block,
}

// Extension method to add a value associated to the enums
extension BroadcastingModeExt on BroadcastingMode {
  String get value {
    switch (this) {
      case BroadcastingMode.sync:
        return 'sync';
      case BroadcastingMode.async:
        return 'async';
      case BroadcastingMode.block:
        return 'block';
      default:
        return null;
    }
  }
}

print(BroadcastingMode.async.value);  // 'async'
```

**Comment by zenit70** [comment]
@pasqenr 

If i use this code `extension BroadcastingModeExt on BroadcastingMode ...`, then i have to update the SDK constraints to `sdk: ">=2.6.0 <3.0.0"`. 

Do you think that's gonna be a problem?

**Comment by pasqenr** [comment]
> @pasqenr
> 
> If i use this code `extension BroadcastingModeExt on BroadcastingMode ...`, then i have to update the SDK constraints to `sdk: ">=2.6.0 <3.0.0"`.
> 
> Do you think that's gonna be a problem?

With the current Flutter stable release (1.17.1) the Dard SDK constraints are:
```yaml
environment:
    sdk: ">=2.7.0 <3.0.0"
```
I think that the update to `2.6.0` should be fine. Otherwise the extension method `BroadcastingModeExt` can be converted as a plain `static` method and placed inside, for example, `lib/utils/utils.dart`.

**Comment by zenit70** [comment]
@pasqenr 

I updated the code following your advice. 

I also updated the files in the 'examples' folder, but it seems to me that this folder doesn't make any sense since there are already examples in the documentation; moreover, it seems to me that there is nothing equivalent in the Kotlin version. Maybe this folder could be removed? 

@marcotradenet

**Comment by pasqenr** [comment]
> @pasqenr
> 
> I updated the code following your advice.
> 
> I also updated the files in the 'examples' folder, but it seems to me that this folder doesn't make any sense since there are already examples in the documentation; moreover, it seems to me that there is nothing equivalent in the Kotlin version. Maybe this folder could be removed?
> 
> @marcotradenet

The code looks good to me. About the `examples` folder I agree, also maintain two separate but equal portions of code is not a good choice, it's easy to forget to update one or another. So, yes, in my opinion we can keep only `docs` because it also has the actual documentation.

**Comment by zenit70** [comment]
@pasqenr
I removed the "examples" folder and updated the method to derive an RSA key (now both public and private) from the PEM string of the class "RSAKeyParser"; could you check if this function is OK?

**Review by pasqenr — APPROVED** [review]
The new implementation of `parseKeyFromPem()` is working flawless for me, nice update.

**Pull request merged**
