### PR TITLE
Update did power up

### LINKED ISSUE #9: Update IdHelper.requestDidPowerUp  function
The 'requestDidPowerUp' function of the 'IdHelper' class must be updated to meet the new [specifications](https://staging.docs.commercio.network/x/id/#did-power-up).

### PR DESCRIPTION
**Pull request by pasqenr**
This PR has the updates the `IdHelper.requestDidPowerUp()` method to meet the new requirements and closes #9 .

This PR also includes:

- Current work from the branch `update-docshare` 
- Removes amount multiplier `MintHelper.openCdp()` (see fa89291)

### CODE REVIEW

**Review by zenit70 — COMMENTED** [review]
@pasqenr  
I had added the 'IdentityResponse' and 'TumblerResponse' classes for parsing the 'getGovernmentRsaPubKey' method response, but it seems to me that you haven't used them; I think you can safely delete them.
@marcotradenet

**Comment by pasqenr** [comment]
> @pasqenr
> I had added the 'IdentityResponse' and 'TumblerResponse' classes for parsing the 'getGovernmentRsaPubKey' method response, but it seems to me that you haven't used them; I think you can safely delete them.
> @marcotradenet

Actually I used them in [lib/crypto/encryption_helper.dart](https://github.com/commercionetwork/commercio-sdk.dart/blob/update-did-power-up/lib/crypto/encryption_helper.dart), added with the commit 000272710b3b3d625d421c1ff58e639e5a40e9f4. I found those classes really helpful to complete  the method.

**Comment by zenit70** [comment]
> Actually I used them in [lib/crypto/encryption_helper.dart](https://github.com/commercionetwork/commercio-sdk.dart/blob/update-did-power-up/lib/crypto/encryption_helper.dart), added with the commit [0002727](https://github.com/commercionetwork/commercio-sdk.dart/commit/000272710b3b3d625d421c1ff58e639e5a40e9f4). I found those classes really helpful to complete the method.

Ok

**Review by marcotradenet — APPROVED** [review]
The name iso8601 is not the most suitable because it concerns the format type 2020-05-18T07:54Z while it is a timestamp format

**Pull request merged**
